"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@arcana/auth";
import { ProvideAuth } from "@arcana/auth-react";

const inter = Inter({ subsets: ["latin"] });

const provider = new AuthProvider(
  "xar_test_8cf0c9eb9f219a444cd2769d3ebd8ccf27b41bb3",
  {
    network: "mainnet",
    theme: "light",
    connectOptions: {
      compact: false,
    },
  }
); //See SDK 

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ProvideAuth provider={provider}>
      <body>{children}</body>
      </ProvideAuth>
    </html>
  );
}
